version: '3'
services:
   cdo-service:
      build:
         context: ./
         dockerfile: ./Dockerfile
      image: 3apag/cdo-service:0.0.1
      ports:
      - 8199:8199
      environment:
         MYSQL_JDBC_URL: jdbc:mysql://mysql-cdo:3306/db?useSSL=false&allowPublicKeyRetrieval=true
         MYSQL_USER: user
         MYSQL_PASSWORD: password
      depends_on:
      - mysql-cdo
      
   mysql-cdo:
      image: mysql
      restart: always
      command: --lower_case_table_names=1
      environment:
         MYSQL_DATABASE: db
         MYSQL_USER: user
         MYSQL_PASSWORD: password
         MYSQL_ROOT_PASSWORD: password
      ports:
      - 3306:3306
      expose:
      - 3306
      volumes:
      - mysql-data:/var/lib/mysql
volumes:
   mysql-data:
      driver: local