apiVersion: v1
kind: Service
metadata:
  name: cdo-service
  labels:
    app: cdo-service
spec:
  ports:
    - name: http
      port: 8199
      targetPort: 8199
  selector:
    app: cdo
  type: NodePort
